In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [3]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [4]:
X = df.drop(columns=["needs_water"])
y = df["needs_water"]

In [5]:
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min)

In [6]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=42)

In [8]:
model = keras.Sequential([
    layers.Input(shape =(X_train.shape[1],)),
    layers.Dense(8,activation = "relu"),
    layers.Dense(1,activation = "sigmoid")
])

In [10]:
model.compile(optimizer = "sgd" , loss = "binary_crossentropy" , metrics = ["accuracy"])

In [15]:
history = model.fit(X_train,y_train,
                    validation_data = (X_test,y_test),
                    epochs = 100,
                    batch_size = 2,
                    verbose = 1)

Epoch 1/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 0.1028 - val_accuracy: 0.7500 - val_loss: 0.2108
Epoch 2/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.1022 - val_accuracy: 0.7500 - val_loss: 0.2116
Epoch 3/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.1033 - val_accuracy: 0.7500 - val_loss: 0.2119
Epoch 4/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.1021 - val_accuracy: 0.7500 - val_loss: 0.2115
Epoch 5/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.1020 - val_accuracy: 0.7500 - val_loss: 0.2121
Epoch 6/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.1027 - val_accuracy: 0.7500 - val_loss: 0.2110
Epoch 7/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.1023 - val_accuracy: 0.7500 - val_loss: 0.2108
Epoch 8/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.1016 - val_accuracy: 0.7500 - val_loss: 0.2104
Epoch 9/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.1021 - val_accuracy: 0.7500 - val_loss: 0.2107
Epoch 10/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.1015 - val_accuracy: 0.7500 - val_loss: 0.2102
Epoch 11/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.1017 - val_accuracy: 0.7500 - val_loss: 0.2097
Epoch 12/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.1015 - val_accuracy: 0.7500 - val_loss: 0.2094
Epoch 13/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.1021 - val_accuracy: 0.7500 - val_loss: 0.2100
Epoch 14/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0998 - val_accuracy: 0.7500 - val_loss: 0.2103
Epoch 15/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.1022 - val_accuracy: 0.7500 - val_loss: 0.2110
Epoch 16/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.1008 - val_accuracy: 0.7500 - val_loss: 0.2112
Epoch 17/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.1017 - val_accuracy: 0.7500 - val_loss: 0.2097
Epoch 18/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.1002 - val_accuracy: 0.7500 - val_loss: 0.2094
Epoch 19/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.1007 - val_accuracy: 0.7500 - val_loss: 0.2093
Epoch 20/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.1008 - val_accuracy: 0.7500 - val_loss: 0.2101
Epoch 21/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.1003 - val_accuracy: 0.7500 - val_loss: 0.2108
Epoch 22/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.1001 - val_accuracy: 0.7500 - val_loss: 0.2114
Epoch 23/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.1010 - val_accuracy: 0.7500 - val_loss: 0.2104
Epoch 24/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0983 - val_accuracy: 0.7500 - val_loss: 0.2105
Epoch 25/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0999 - val_accuracy: 0.7500 - val_loss: 0.2100
Epoch 26/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0993 - val_accuracy: 0.7500 - val_loss: 0.2098
Epoch 27/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0993 - val_accuracy: 0.7500 - val_loss: 0.2098
Epoch 28/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0983 - val_accuracy: 0.7500 - val_loss: 0.2094
Epoch 29/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.1002 - val_accuracy: 0.7500 - val_loss: 0.2101
Epoch 30/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.1004 - val_accuracy: 0.7500 - val_loss: 0.2095
Epoch 31/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.0996 - val_accuracy: 0.7500 - val_loss: 0.2103
Epoch 32/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0992 - val_accuracy: 0.7500 - val_loss: 0.2103
Epoch 33/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0992 - val_accuracy: 0.7500 - val_loss: 0.2101
Epoch 34/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0999 - val_accuracy: 0.7500 - val_loss: 0.2094
Epoch 35/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0992 - val_accuracy: 0.7500 - val_loss: 0.2098
Epoch 36/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0989 - val_accuracy: 0.7500 - val_loss: 0.2087
Epoch 37/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0990 - val_accuracy: 0.7500 - val_loss: 0.2095
Epoch 38/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0986 - val_accuracy: 0.7500 - val_loss: 0.2102
Epoch 39/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0982 - val_accuracy: 0.7500 - val_loss: 0.2100
Epoch 40/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0987 - val_accuracy: 0.7500 - val_loss: 0.2101
Epoch 41/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0969 - val_accuracy: 0.7500 - val_loss: 0.2099
Epoch 42/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0993 - val_accuracy: 0.7500 - val_loss: 0.2100
Epoch 43/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.0981 - val_accuracy: 0.7500 - val_loss: 0.2101
Epoch 44/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.0968 - val_accuracy: 0.7500 - val_loss: 0.2095
Epoch 45/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0988 - val_accuracy: 0.7500 - val_loss: 0.2091
Epoch 46/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0976 - val_accuracy: 0.7500 - val_loss: 0.2094
Epoch 47/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0976 - val_accuracy: 0.7500 - val_loss: 0.2090
Epoch 48/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.0986 - val_accuracy: 0.7500 - val_loss: 0.2077
Epoch 49/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0982 - val_accuracy: 0.7500 - val_loss: 0.2081
Epoch 50/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0989 - val_accuracy: 0.7500 - val_loss: 0.2084
Epoch 51/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0971 - val_accuracy: 0.7500 - val_loss: 0.2091
Epoch 52/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0975 - val_accuracy: 0.7500 - val_loss: 0.2098
Epoch 53/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0978 - val_accuracy: 0.7500 - val_loss: 0.2087
Epoch 54/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0980 - val_accuracy: 0.7500 - val_loss: 0.2085
Epoch 55/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.0972 - val_accuracy: 0.7500 - val_loss: 0.2088
Epoch 56/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0966 - val_accuracy: 0.7500 - val_loss: 0.2085
Epoch 57/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 0.0976 - val_accuracy: 0.7500 - val_loss: 0.2091
Epoch 58/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.0974 - val_accuracy: 0.7500 - val_loss: 0.2086
Epoch 59/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0953 - val_accuracy: 0.7500 - val_loss: 0.2086
Epoch 60/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0962 - val_accuracy: 0.7500 - val_loss: 0.2089
Epoch 61/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0974 - val_accuracy: 0.7500 - val_loss: 0.2078
Epoch 62/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0967 - val_accuracy: 0.7500 - val_loss: 0.2079
Epoch 63/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0970 - val_accuracy: 0.7500 - val_loss: 0.2086
Epoch 64/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0970 - val_accuracy: 0.7500 - val_loss: 0.2090
Epoch 65/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.0964 - val_accuracy: 0.7500 - val_loss: 0.2082
Epoch 66/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 0.0969 - val_accuracy: 0.7500 - val_loss: 0.2073
Epoch 67/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.0962 - val_accuracy: 0.7500 - val_loss: 0.2077
Epoch 68/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0959 - val_accuracy: 0.7500 - val_loss: 0.2076
Epoch 69/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0968 - val_accuracy: 0.7500 - val_loss: 0.2070
Epoch 70/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0959 - val_accuracy: 0.7500 - val_loss: 0.2064
Epoch 71/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.0965 - val_accuracy: 0.7500 - val_loss: 0.2073
Epoch 72/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.0965 - val_accuracy: 0.7500 - val_loss: 0.2080
Epoch 73/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 0.0956 - val_accuracy: 0.7500 - val_loss: 0.2087
Epoch 74/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.0950 - val_accuracy: 0.7500 - val_loss: 0.2084
Epoch 75/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0938 - val_accuracy: 0.7500 - val_loss: 0.2079
Epoch 76/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0952 - val_accuracy: 0.7500 - val_loss: 0.2085
Epoch 77/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 1.0000 - loss: 0.0959 - val_accuracy: 0.7500 - val_loss: 0.2079
Epoch 78/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0944 - val_accuracy: 0.7500 - val_loss: 0.2083
Epoch 79/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0944 - val_accuracy: 0.7500 - val_loss: 0.2082
Epoch 80/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0944 - val_accuracy: 0.7500 - val_loss: 0.2083
Epoch 81/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0957 - val_accuracy: 0.7500 - val_loss: 0.2079
Epoch 82/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0947 - val_accuracy: 0.7500 - val_loss: 0.2074
Epoch 83/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0950 - val_accuracy: 0.7500 - val_loss: 0.2082
Epoch 84/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0941 - val_accuracy: 0.7500 - val_loss: 0.2071
Epoch 85/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0930 - val_accuracy: 0.7500 - val_loss: 0.2072
Epoch 86/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0952 - val_accuracy: 0.7500 - val_loss: 0.2076
Epoch 87/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.0945 - val_accuracy: 0.7500 - val_loss: 0.2073
Epoch 88/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0944 - val_accuracy: 0.7500 - val_loss: 0.2068
Epoch 89/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0949 - val_accuracy: 0.7500 - val_loss: 0.2072
Epoch 90/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0926 - val_accuracy: 0.7500 - val_loss: 0.2076
Epoch 91/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0945 - val_accuracy: 0.7500 - val_loss: 0.2081
Epoch 92/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0940 - val_accuracy: 0.7500 - val_loss: 0.2077
Epoch 93/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0945 - val_accuracy: 0.7500 - val_loss: 0.2075
Epoch 94/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0937 - val_accuracy: 0.7500 - val_loss: 0.2070
Epoch 95/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0932 - val_accuracy: 0.7500 - val_loss: 0.2068
Epoch 96/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.0938 - val_accuracy: 0.7500 - val_loss: 0.2059
Epoch 97/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0936 - val_accuracy: 0.7500 - val_loss: 0.2064
Epoch 98/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0935 - val_accuracy: 0.7500 - val_loss: 0.2065
Epoch 99/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.0938 - val_accuracy: 0.7500 - val_loss: 0.2069
Epoch 100/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.0930 - val_accuracy: 0.7500 - val_loss: 0.2058